# Generated by Django 2.2.4 on 2019-11-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Admin Approval'), ('Registered', 'Approved by Admin')], default='Pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='completed',
            field=models.ManyToManyField(blank=True, to='core.Prompt'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='description',
            field=models.TextField(blank=True, help_text='Leave blank to suggest users to refer to the PDF.'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='ref',
            field=models.PositiveIntegerField(verbose_name='Question #'),
        ),
    ]
