# Generated by Django 2.2.4 on 2019-11-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Access code has not been used'), ('Active', 'Access code has been used')], default='Inactive', max_length=32),
        ),
    ]
